---
name: CI
permissions: {}

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build Jekyll
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a  # v1.302.0
        with:
          ruby-version: '3.3'

      - name: Install dependencies
        run: bundle install && bundle exec appraisal install

      - name: Setup Pages
        id: configure-pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d  # v6.0.0

      - name: Setup CI config
        run: |
          echo "---" > _config_ci.yml
          echo "baseurl: '${{ steps.configure-pages.outputs.base_path }}'" >> _config_ci.yml

      - name: Build site
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAGES_REPO_NWO: ${{ github.repository }}
        run: bundle exec appraisal jekyll build --future --config _config_ci.yml,_config.yml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  # v5.0.0
